### ISSUE TITLE
I can't see play button in course introductory videos

### ISSUE THREAD

**Issue by mariajgrimaldi** [overhangio/tutor-indigo#104]
### Description

When configuring an introductory video for a course, I can't see the play button on the course about page which makes it appear like there's none configured:

[Screencast from 18-11-24 17:14:04.webm](https://github.com/user-attachments/assets/68dda902-a9f1-4844-b5db-d30515e2ab72)

I tested this locally in my tutor environment without indigo, and the play button was displayed as it should.

Originally reported here: https://github.com/openedx/wg-build-test-release/issues/408

**Comment by hinakhadim** [comment]
Hi @mariajgrimaldi,
Thanks for the issue. We've updated the theme and now the Youtube Icon is visible. 
Sandbox: https://sumac.demo.edly.io/courses/course-v1:edSPIRIT+ES101+2025_T1/about
