### ISSUE TITLE
Dark Mode Issues: Unreadable ORA Elements and Visibility Problems

### ISSUE THREAD

**Issue by magajh** [overhangio/tutor-indigo#107]
## Description

This issue highlights several problems with the dark mode implementation in the Tutor-Indigo theme. These issues affect the readability and usability of specific sections in the Open edX platform when dark mode is enabled. They were originally flagged during the Sumac release testing but have been identified as theme-specific and tied to Indigo.

During a recent BTR meeting, it was decided that theme-specific testing, such as addressing dark mode issues in the Indigo theme, would be under the responsibility of the theme maintainers. You can find more details here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/4551147558/2024-11-04+BTR+Meeting+Minutes. Below are the details of the reported issues:

---

#### **1. ORA Response and Rubric Colors Render Unreadable**
- **Expected Behavior:** 
  All parts of the Open Response Assessment (ORA) interface should be easily readable in dark mode.
- **Actual Behavior:** 
  Some text and UI elements within the ORA become difficult to read or entirely invisible due to incompatible colors in the dark mode color scheme.
[https://jam.dev/c/0590feb8-01b0-455c-8ef1-b40fbf8f3780)](https://jam.dev/c/0590feb8-01b0-455c-8ef1-b40fbf8f3780)
- **Original Report:**
  - https://github.com/openedx/wg-build-test-release/issues/402

---

#### **2. Dark Mode Compatibility Issues Across Handouts and Updates Sections**
- **Expected Behavior:** 
  All interface sections, including Handouts and Updates, should be readable and visually compatible with dark mode settings.
- **Actual Behavior:** 
  Handouts and Updates sections display a white background, leading to a jarring visual mismatch and reduced readability.
- **Original Report:**
  - https://github.com/openedx/wg-build-test-release/issues/410

**Comment by mariajgrimaldi** [comment]
This issue might be related to the dark/light options as well: https://github.com/overhangio/tutor-indigo/issues/108

**Comment by hinakhadim** [comment]
Part 1: "ORA Response and Rubric Colors Render Unreadable" [PR](https://github.com/overhangio/tutor-indigo/pull/111) is ready.

**Comment by hinakhadim** [comment]
[PR](https://github.com/overhangio/tutor-indigo/pull/112/) to fix "**Course Updates and Handouts**" is ready.

**Comment by DawoudSheraz** [comment]
ORA Dark theme fixups are now live on sandbox https://apps.sumac.demo.edly.io/learning/course/course-v1:Test+tc001+2024/block-v1:Test+tc001+2024+type@sequential+block@1332ed90062f494db229a95e83723982/block-v1:Test+tc001+2024+type@vertical+block@b820b6e89ec34c82ad02280a96154273

![image](https://github.com/user-attachments/assets/b4d889b4-e6cf-4937-8a42-dbf595d9eb18)

**Comment by DawoudSheraz** [comment]
PR to fix teams tab dark theme compatibility issues https://github.com/overhangio/tutor-indigo/pull/114
