### ISSUE TITLE
The dropdown component is not displaying the selected option correctly

### ISSUE THREAD

**Issue by mariajgrimaldi** [overhangio/tutor-indigo#108]
The options are barely visible in light mode. I've tested this in a sumac environment without indigo and it works as expected, so my first guess is that it's related to the indigo theme. Let me know if you think otherwise, thanks!

### Expected behavior

When selecting an option in the dropdown component for common problems, the selected option should be displayed correctly.

### Actual behavior

Currently, the selected option in the dropdown is displaying as white in the light theme, making it difficult to see properly.

### Steps to reproduce

1. Add a dropdown common problem.
2. Ensure the light theme is configured.
3. Check if the selected option is displayed correctly.

### Additional information

![Screenshot From 2024-11-14 09-38-53](https://github.com/user-attachments/assets/98e5a33b-ea46-4571-a29a-8ba49a9cad57)

Originally reported here: https://github.com/openedx/wg-build-test-release/issues/419

**Comment by DawoudSheraz** [comment]
Created https://github.com/overhangio/tutor-indigo/pull/110 to fix this.

**Comment by DawoudSheraz** [comment]
This has been resolved and is now live on sandbox 
cc @mariajgrimaldi 
![image](https://github.com/user-attachments/assets/1dc76ff4-455b-4ff8-a6d3-30df1f73ad6a)
