### ISSUE TITLE
Errors are not displayed correctly in extensions tab

### ISSUE THREAD

**Issue by mariajgrimaldi** [overhangio/tutor-indigo#113]
### Description

We believe there's a mishandling of error responses somewhere in the theme, which causes the `object [Object]` to be displayed instead of the response error message.

### Expected behavior

As a course author, I want to know the errors in my input when I try to extend individual due dates or reset extensions.

### Actual behavior

As a course author, I cannot see the errors in my input when I try to extend individual due dates or reset extensions.

### Steps to reproduce

1. From Studio create a new Subsection.
2. Configure it with an assignment type for grading and assign a due date.
3. Go to the **LMS** > **Instructor** > **Extensions** > **Individual Due Date Extensions** or **Resetting Extensions**.

Errors are currently not displaying correctly for the following cases:
1. Specify an email or username that doesn't exist.
2. Specify an invalid date format.
3. Do not specify anything.

https://github.com/user-attachments/assets/f3c93d69-477f-442c-a090-12ecdd77f779

> [!NOTE]  
> The functionality of **Individual Due Date Extensions** and **Resetting Extensions** works. 

### Additional information

In Redwood this is the behavior (without tutor-indigo):

https://github.com/user-attachments/assets/c49cc9f5-19b2-4965-b2df-0ac14258592c

Originally reported here: https://github.com/openedx/wg-build-test-release/issues/422

**Comment by DawoudSheraz** [comment]
@mariajgrimaldi Hi. If I remember correctly from yesterday's meet, Farhan had suggested this might be parsing issue and not theme issue. Indigo is updating styles and not changing any request patterns. We will investigate this but it does not appear to be a theme issue. Were you able to confirm this does not happen locally without indigo enabled?

cc: @hinakhadim

**Comment by mariajgrimaldi** [comment]
@DawoudSheraz: I misunderstood the discussion we had.

I haven't had time to work on this, but I'll take a look again considering what you said.

Please, feel free to close this issue. I'll look into it next week when I'm back.

I'm sorry for the misunderstanding. Thank you!
