### ISSUE TITLE
I m facing issue while adding this theme to my latest installations

### ISSUE THREAD

**Issue by manojkumarhr** [overhangio/tutor-indigo#20]
I am using Tutor 13.2.0 Version and i am facing this issue after typing "tutor plugins enable indigo" Please help me i am new to Tutor and openedx
![tutor indigo error](https://user-images.githubusercontent.com/7630852/164993213-ffb1e77b-adb5-417c-828d-3d384d0ea7f2.png)

**Comment by regisb** [comment]
See: https://github.com/overhangio/tutor/issues/651#issuecomment-1108114360

(you should almost certainly upgrade your version of tutor)
