### ISSUE TITLE
Use django templates

### ISSUE THREAD

**Issue by cristianMeli** [overhangio/tutor-indigo#36]
Hi there!

I am trying to use this plugin as a starting point for my own theme plugin.
I have my own templates (for lms), so what I did was to copy them inside `templates/indigo/lms/templates`.
The issue is that after installing and enabling the plugin, when I do `tutor config save` I get this error: `jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'load'`.
That is because I have Django templates with `{% load i18n %}` declarations and some others.

So my question is: It is possible to use Django templates in my tutor theme plugin?

I saw [here](https://discuss.overhang.io/t/change-edx-logo-in-activation-mail/1238) a possible workaround, that is use `{% raw %}` and `{% endraw %}` tags .
I don't know if this is the right way to use Django templates or if I am missing some configuration.

Regards!!

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/
