### ISSUE TITLE
How can I  customize the header.html

### ISSUE THREAD

**Issue by darda-veostr** [overhangio/tutor-indigo#39]
Hi, There i s no header.html file in this theme . I want change the header with more nav links and search bar . How can I do that?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
