### ISSUE TITLE
It's not clear how to implement a new theme

### ISSUE THREAD

**Issue by throwaway-a** [overhangio/tutor-indigo#44]
I lost a couple hours today brute forcing combinations of tutor commands to try and find the correct way to get changes to appear near-immediately within a tutor instance (I'm not sure why sometimes they took a few minutes after launch before they were reflected, but perhaps it was a Google Chrome cache issue.)

I finally landed on the following set of commands to explicitly apply changes after they were made from within the theme folder:

```
tutor config save
tutor images build openedx
tutor local launch
```

Please update the Configuration or Customization sections of the documentation to explicitly state this is the correct way to apply new changes to the theme.

Also the documentation of "This plugin can serve as a starting point to create your own themes. Just fork this repository and modify the files as you see fit." is incomplete to the point of incorrectness. But I was able to follow the steps from [here](https://discuss.openedx.org/t/tutor-indigo-theme-with-new-plugin/7673) to create my own-named theme (so I could confirm it's what was actually being used). It'd be good if you could extract the important bits from those steps and add them to the documentation too.

**Comment by Edim7** [comment]
I am also having issues with editing a theme and not seeing changes on the site. When I do config save I get all of my changes to the theme folder overwritten and now I'm guessing this has to do with the config. In the end I just wanted to say that further clarification of working with themes would be much appreciated.
