### ISSUE TITLE
Customizing fonts

### ISSUE THREAD

**Issue by FatemeKhodayari** [overhangio/tutor-indigo#46]
Hi. I'm using tutor with openedx olive. As stated in the tutor documentation I used this theme as a base for making my own custom theme. I successfully changed the logo but the font is partially changed. In some sections I see my own font and in some other sections (usually buttons and pages other than the homepage) I still see the default font. 

To change the font, I followed these steps:
1. added custom fonts to a directory within the theme directory
2. added fonts using `font-face` in `lms/static/sass/partials/lms/theme/_fonts.scss`
3. updated `font-family-title`, `serif` and `f-sans-serif` in `_variables.scss`

So where is the other font coming from? Is it from `edx-boostrap` that's imported in `_variables.scss`? Assuming this is the issue, I forked `edx-bootstrap` and changed the fonts there as well. Then I added my own bootstrap (using github link not npm package yet) in openedx-platform package.json file. But now when I want to replace `edx-bootstrap` with my own bootstrap in the `_variables.scss` file, when building the image, I get errors saying my bootstrap does not exist and is not found. So does tutor (indigo) has it's own package.json or something like this? Is there any other way for adding a package to package.json file except adding it to openedx-platform and building the image? Is there any other way of changing fonts globally?

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

**Comment by FatemeKhodayari** [comment]
I don't think this is a feature request. Actually lack of documentation has led to this issue so please consider it a bug (fonts not getting changed completely) or documentation being incomplete on this matter.

**Comment by regisb** [comment]
Indeed, your initial message was not a feature request, but a request for support. The Open edX forum is a better place for these discussions, as explained here: https://docs.tutor.overhang.io/troubleshooting.html
