### ISSUE TITLE
Override or Create New Stylesheet in Indigo Theme

### ISSUE THREAD

**Issue by allenluna** [overhangio/tutor-indigo#58]
Hi I am new to open edx platform, Want to override or create my own stylesheet in the indigo theme that I clone here [GitHub - overhangio/tutor-indigo: An elegant, customizable theme for Open edX](https://github.com/overhangio/tutor-indigo) and I follow the instructions, I also try to edit the _extras.scss in here and do the local images build openedx followed by tutor local start -d \tutor\env\build\openedx\themes\indigo\lms\static\sass\partials\lms\theme but still has no effect, and every time that I use tutor config save the style that I set or change in the _extras.scss always erase, can someone help me to edit the styles ?

![image](https://github.com/overhangio/tutor-indigo/assets/126066409/e46eaba6-bc69-45b5-be21-baa2389e3b0b)

![image](https://github.com/overhangio/tutor-indigo/assets/126066409/57c85f1b-08e3-4dc0-9cc3-e0a563013566)

thank you

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
