### ISSUE TITLE
If using a custom theme Powered By Logos do no render

### ISSUE THREAD

**Issue by misilot** [overhangio/tutor-indigo#65]
On the apps MFE pages

Go to course details if you enroll or view an open course, the Runs on Tutor and Powered by Open edX logos are tied to the `tutor` theme and not a custom one that has been forked, and the images do not render.

Example from: https://apps.test.online.newliteraciesalliance.org/learning/course/course-v1:NLA+IL1015+20_21/home

<img width="991" alt="image" src="https://github.com/overhangio/tutor-indigo/assets/1446856/a670d8af-dc2d-4caa-9951-f2c8b39141f7">

```
<div class="footer-top"><div class="powered-area"><ul class="logo-list"><li>Powered by</li><li><a href="https://docs.tutor.overhang.io" rel="noreferrer" target="_blank"><img src="https://test.online.newliteraciesalliance.org/static/indigo/images/tutor-logo.png" alt="Runs on Tutor" width="57" class=""></a></li><li><a href="https://open.edx.org" rel="noreferrer" target="_blank"><img src="https://test.online.newliteraciesalliance.org/static/indigo/images/openedx-logo.png" alt="Powered by Open edX" width="79" class=""></a></li></ul></div></div><span class="copyright-site">Copyrights ©2023. All Rights Reserved.</span>
```

**Comment by misilot** [comment]
Looks like it is from this MFE?

https://github.com/edly-io/frontend-component-footer/blob/quince/indigo/src/components/Footer.jsx#L58
https://github.com/edly-io/frontend-component-footer/blob/quince/indigo/src/components/Footer.jsx#L67

**Comment by hinakhadim** [comment]
Thanks to @misilot for resolving, [PR Link](https://github.com/edly-io/frontend-component-footer/pull/8) .
