### ISSUE TITLE
tutor-indigo codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-indigo#72]
- [x] Ensure tutor-indigo codebase is compatible with Python 3.12
- ~~Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly~~ N/A  

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by hinakhadim** [comment]
This plugin doesn't have any of its own Dockerfile. It makes changes to `mfe` Dockerfile by including `indigo-brand`, `indigo-header` and `indigo-footer` packages. Tested the nightly branch with python 3.12 and it is compatible.
