### ISSUE TITLE
Faint unexpected rectangle in the course about page

### ISSUE THREAD

**Issue by mariajgrimaldi** [overhangio/tutor-indigo#81]
### Expected behavior

Not 100% sure - this might actually be a design choice rather than a bug.

### Actual behavior

There's a light-colored rounded rectangle behind and offset from the course image. I'm not 100% sure that's intentional - not sure whether it's supposed to be there or directly behind the image.

<img width="1082" alt="Screenshot 2024-05-17 at 9 47 22 AM" src="https://github.com/openedx/wg-build-test-release/assets/1929508/539850bb-cffd-4311-8578-d5c23680b66c">

### Steps to reproduce

Just visit any About page.

### Additional information

In ones without an image you get a blank square in front of the rectangle.

<img width="1126" alt="Screenshot 2024-05-17 at 9 48 06 AM" src="https://github.com/openedx/wg-build-test-release/assets/1929508/4388f1f6-405e-4e39-a47a-492d4a90834b">

Original issue: https://github.com/openedx/wg-build-test-release/issues/345

I'm opening this issue to confirm whether this is a design choice or a bug. I'm unfamiliar with the indigo theme, so I can't say for sure.

**Comment by mariajgrimaldi** [comment]
label: release testing

**Comment by mariajgrimaldi** [comment]
Well, that didn't work 😅.

**Comment by DawoudSheraz** [comment]
@hinakhadim FYI

**Comment by DawoudSheraz** [comment]
> Well, that didn't work 😅.
I think this is because the repo is in overhangio organization and not Open edX.

**Comment by hinakhadim** [comment]
Hi @mariajgrimaldi ,

This is a design choice. The rectangle position is also correct and it won't be just behind the image.

However, the second screenshot is a bug. There should be the thumbnail/fallback course image in case of no course image.

**Comment by hinakhadim** [comment]
This [PR](https://github.com/overhangio/tutor-indigo/pull/80) will resolve the second screenshot (bug).
