### ISSUE TITLE
Sidebar navigation, discussions, or notifications take over half the width of the page when Indigo theme is used

### ISSUE THREAD

**Issue by GlugovGrGlib** [overhangio/tutor-indigo#83]
## Description
This issue was reported as part of Redwood release platform. Because the indigo theme [is enabled by default since Quince release](https://github.com/overhangio/tutor/blob/master/tutor/templates/config/base.yml#L8-L11) for all Tutor deployments, this issue is considered a major problem for Open edX. 

The original issue found during release testing  - https://github.com/openedx/frontend-app-learning/issues/1401

Please find more info about a possible technical solution in the comment: https://github.com/openedx/frontend-app-learning/issues/1401#issuecomment-2148622086

## Steps to Reproduce

1. Login to an instance using the Indigo theme as an admin user to ensure the `courseware.enable_navigation_sidebar` waffle flag is enabled
1. Navigate to an in-course experience page
1. With the sidebar navigation expanded, view the page

## Expected Behavior

1. The sidebar navigation when expanded takes up much less than half of the page horizontally (see attached image from an in-course experience page using the Open edX theme)
1. There is a reasonable amount of blank space on either side of the course content/sidebar content

### Default Open edX theme:
![image](https://github.com/overhangio/tutor-indigo/assets/22370912/8caf9924-d137-4708-97c1-ba186c7a204f)

## Actual Behavior

1. The sidebar navigation when expanded takes up half of the page horizontally (see attached image from an in-course experience page using the Indigo theme)
1. There is a lot of extra blank space on either side of the course content/sidebar content

### Full HD:
![image](https://github.com/overhangio/tutor-indigo/assets/22370912/ecf60bc2-91ad-4cd8-920d-a751f06f3e4a)

### Wide screen:
<img width="2992" alt="image" src="https://github.com/overhangio/tutor-indigo/assets/22370912/28efb547-549f-44d3-b938-2a6012b705b6">

**Comment by GlugovGrGlib** [comment]
@DawoudSheraz FYI about this product request

**Comment by DawoudSheraz** [comment]
Thanks @GlugovGrGlib 
FYI @hinakhadim

**Comment by hinakhadim** [comment]
Hi @GlugovGrGlib , 
Thanks for taking time and identifying this. This [PR](https://github.com/overhangio/tutor-indigo/pull/85) will resolve this issue with tutor-indigo version `17.4.0`.
