### ISSUE TITLE
Unable to install indigo

### ISSUE THREAD

**Issue by thasipablo** [overhangio/tutor-indigo#98]
I am on Ubuntu Desktop 24.04 LTS, Python 3.12.3, tutor 18.1.3

I was unable to install indigo using the command `tutor plugins install indigo` since it installs system-wide.
I had to install it using `pip install tutor-indigo --break-system-packages`

1. with `tutor plugins install indigo`

![image](https://github.com/user-attachments/assets/c29897d3-ac9f-43ef-b1cd-b814e60589ac)

2. with `pip install tutor-indigo --break-system-packages`

![image](https://github.com/user-attachments/assets/372d7169-1f81-40f6-a10c-de20e6892d63)

3. result

![image](https://github.com/user-attachments/assets/2e9c48a6-e9a8-4442-8560-5c48ef8d02e6)

**Comment by hinakhadim** [comment]
Thanks for the details. It seems you are trying to install the package without activating the virtual environment. Could you please answer the following questions to assist you better?
- Are you using a virtual environment? If yes, Have you activated it?
-  Did you try installing any other Tutor plugins? If so, did you face similar issues?
- Do you have administrative or sudo privileges on the system?
- Can you share your current Python environment and PATH configuration?

**Comment by thasipablo** [comment]
Hi @hinakhadim 

I have sudo and full privileges on the system. I tried to install the package in the conda virtual environment but the tutor couldn't find it until I installed it system-wide.

**Comment by regisb** [comment]
As I explained in my answer to your Youtube command, you should not ever ever install tutor with sudo. Please watch again https://youtu.be/dTHHeEXu2c8?feature=shared&t=348
