### ISSUE TITLE
Redirect to Login Page When User Sign Out

### ISSUE THREAD

**Issue by hamzaCraftsCode** [overhangio/tutor-indigo#99]
Hi veryone,
I want to customize my edx. When a user signs out, instead of going to the [discover courses page](https://edx.data-pilot.com/) page it should go to the [login page](https://apps.edx.data-pilot.com/authn/login?next=%2F)

For this I have tried changing the user_dropdown.html file. I changed the href in

`<div class="mobile-nav-item dropdown-item dropdown-nav-item"><a href="${reverse('logout')}" role="menuitem">${_("Sign Out")}</a></div>`
to

`<div class="mobile-nav-item dropdown-item dropdown-nav-item"><a href="/login${login_query()}" role="menuitem">${_("Sign Out")}</a></div>`

but it did not work.
After some research I have to a conclusion that

1. Maybe I have to create mfe plugin to do this
2. Maybe I have to make some changes in the caddy file
3. Maybe I have to add a route somewhere

Please guide me on this.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/ Make sure to include as much information as possible about your use case.
